version: '3'
services:
  db:
    image: r888888888/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    command: memcached
  archives:
    image: r888888888/archives
    command: sleep 1d
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - RAILS_ENV
      - AMAZON_KEY
      - AMAZON_SQS_REGION
      - AMAZON_SECRET
      - SQS_ARCHIVES_URL
      - RUN
    depends_on:
      - db
  web:
    environment:
      - SECRET_TOKEN
      - SESSION_SECRET_KEY
      - RAILS_ENV
      - DATABASE_URL
      - RO_DATABASE_URL
      - DEBUG
      - ARCHIVE_DATABASE_URL
      - DANBOORU_MEMCACHED_SERVERS
      - DANBOORU_AWS_SQS_ARCHIVE_URL
      - DANBOORU_PIXIV_LOGIN
      - DANBOORU_PIXIV_PASSWORD
      - DANBOORU_TWITTER_API_KEY
      - DANBOORU_TWITTER_API_SECRET
      - DANBOORU_AWS_ACCESS_KEY_ID
      - DANBOORU_AWS_SECRET_ACCESS_KEY
      - DANBOORU_AWS_SQS_REGION
      - DANBOORU_NIJIE_LOGIN
      - DANBOORU_NIJIE_PASSWORD
      - DANBOORU_NICO_SEIGA_LOGIN
      - DANBOORU_NICO_SEIGA_PASSWORD
      - DANBOORU_PERSIST_PIXIV_SESSION
      - DANBOORU_TUMBLR_CONSUMER_KEY
      - CIRCLE_NODE_TOTAL
      - CIRCLE_NODE_INDEX
      - CIRCLE_BUILD_IMAGE
    build: 
      context: ../..
      dockerfile: config/docker/danbooru-ci
    command: sleep 1d
    ports:
      - "3000:3000"
    depends_on:
      - db
      - memcached
      - archives
      - redis
