name: Load Docker Image
description: Load Docker Image

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        load: true
        tags: e621:test

    - name: Set docker run command
      run: echo "DOCKER_RUN=docker run --rm --network host -e POSTGRES_HOST=localhost -e RAILS_ENV=test -e CI=true -v $PWD:/app e621:test" >> "$GITHUB_ENV"
      shell: bash
