name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign it') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures.json'
          path-to-document: 'https://github.com/e621ng/e621ng/blob/master/CLA.md'
          branch: 'util/contributors'
          allowlist: film-projector,Sindrake,bot*
          custom-notsigned-prcomment: "Thank you for your submission, we really appreciate it.\n\nLike many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/e621ng/e621ng/blob/master/CLA.md) before we can accept your contribution.\nYou can sign the CLA by making a comment following the format below:"
          custom-pr-sign-comment: "I have read the CLA Document and I hereby sign it"
